export { createObsidianClient } from "./core/client";
export {
  captureFailureArtifacts,
  DEFAULT_FAILURE_ARTIFACTS_DIR,
} from "./artifacts/failure-artifacts";
export { createTestContext, withVaultSandbox } from "./fixtures/test-context";
export {
  acquireVaultRunLock,
  clearVaultRunLockMarker,
  inspectVaultRunLock,
  readVaultRunLockMarker,
} from "./fixtures/vault-lock";
export type {
  CommandListOptions,
  CommandTransport,
  CreateObsidianClientOptions,
  DevConsoleMessage,
  DevDiagnostics,
  DevDomQueryOptions,
  DevDomResult,
  DevNoticeEvent,
  DevRuntimeError,
  ExecOptions,
  ExecResult,
  JsonFile,
  JsonFileUpdater,
  MetadataFileCache,
  MetadataWaitOptions,
  MetadataPredicate,
  NoteDocument,
  NoteFrontmatter,
  NoteInput,
  NoteMatcherOptions,
  ObsidianArg,
  ObsidianAppHandle,
  ObsidianClient,
  ObsidianCommandHandle,
  ObsidianDevHandle,
  ObsidianMetadataHandle,
  OpenFileOptions,
  OpenTabOptions,
  PluginHandle,
  PluginDataPredicate,
  PluginReloadOptions,
  PluginUpdateDataOptions,
  PluginWithPatchedDataOptions,
  RestartAppOptions,
  SandboxApi,
  TabsOptions,
  VaultApi,
  VaultContentPredicate,
  VaultWaitForContentOptions,
  VaultWriteOptions,
  WaitForOptions,
  WorkspaceNode,
  WorkspaceOptions,
  WorkspaceTab,
  PluginWaitForDataOptions,
  PluginWaitUntilReadyOptions,
} from "./core/types";
export type {
  CaptureFailureArtifactsOptions,
  FailureArtifactConfig,
  FailureArtifactOptions,
  FailureArtifactRegistrationOptions,
  FailureArtifactTask,
} from "./artifacts/failure-artifacts";
export type {
  AcquireVaultRunLockOptions,
  VaultRunLock,
  VaultRunLockMetadata,
  VaultRunLockState,
} from "./fixtures/vault-lock";
export type {
  CreatePluginTestOptions,
  CreateObsidianTestOptions,
  ObsidianFixtures,
  ObsidianTest,
  PluginFixtures,
  PluginSessionOptions,
  PluginTest,
  SharedVaultLockOptions,
  TestContext,
  TestContextCleanupOptions,
  VaultSeed,
  VaultSeedEntry,
} from "./fixtures/types";
export { createNoteDocument, parseNoteDocument, stringifyNoteDocument } from "./note/document";
export { createSandboxApi } from "./vault/sandbox";
export { createVaultApi } from "./vault/vault";
